package fuzzcommons;

import java.io.Serializable;

public class Command implements Serializable{

	/**
	 * Autogenerated
	 */
	private static final long serialVersionUID = 4114361269262059581L;

	public enum CommandType { DO, QUERY_CLASS, QUERY_METHOD, INITIATE}; 
	private CommandType commandType;
	private String name;
	private Class<?>[] argTypes;
	private Object[] argValues;
	
	public Command(CommandType commandType, String name, Class<?>[] argTypes,
			Object[] argValues) {
		this.commandType = commandType;
		this.name = name;
		this.argTypes = argTypes;
		this.argValues = argValues;
	}

	public CommandType getCommandType() {
		return commandType;
	}

	public void setCommandType(CommandType commandType) {
		this.commandType = commandType;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Class<?>[] getArgTypes() {
		return argTypes;
	}

	public void setArgTypes(Class<?>[] argTypes) {
		this.argTypes = argTypes;
	}

	public Object[] getArgValues() {
		return argValues;
	}

	public void setArgNames(Object[] argValues) {
		this.argValues = argValues;
	}
	
	
	
	
}
