package fuzzcommons;

import java.io.Serializable;

public class HelloBye implements Serializable {
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = 1733026154820655040L;

	public enum Greeting {
		HELLO, GOODBYE
	};

	private Greeting greeting;
	private String className;

	public HelloBye(Greeting greeting) {
		this.greeting = greeting;
	}
	
	public HelloBye(Greeting greeting, String className) {
		this.greeting = greeting;
		this.className = className;
	}

	public Greeting getGreeting() {
		return greeting;
	}

	public void setGreeting(Greeting greeting) {
		this.greeting = greeting;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

}